Mariasirley tg
khriztianmoreno/fullstack-js-makeitreal pull request #24
Opened 2020-12-15 23:30 UTC by Mariatangarife1998

modificacion del archivo Readmi

2020-12-15 23:32 UTC, khriztianmoreno requested changes
Por favor resolver los conflictos antes de fusionar. Excelente trabajo

2020-12-15 23:33 UTC, Mariatangarife1998 commented
> Por favor resolver los conflictos antes de fusionar. Excelente trabajo

listo profe ya lo hago

2020-12-15 23:33 UTC, khriztianmoreno commented on README.md
> +
Resolver el conflicto incluyendo la linea de alejandro becerra

2020-12-16 01:03 UTC, khriztianmoreno approved these changes
Felicitaciones 🥇

2020-12-16 01:07 UTC, merged