Daniel Alvarez JS01
khriztianmoreno/fullstack-js-makeitreal pull request #81
Opened 2021-01-15 02:00 UTC by Dansata

2021-01-15 13:16 UTC, khriztianmoreno requested changes
Hola Daniel, te falto agregar al commit el archivo `alert.js`

2021-01-18 21:49 UTC, khriztianmoreno approved these changes

2021-01-18 21:49 UTC, khriztianmoreno commented on daniel_alvarez/js-hello-world/index.html
> +    <script src="alert.js"></script>
Mi recomendacion es que este script deberia ir antes de cerrar la etiqueta body, asi podriamos evitarnos muchos lios

2021-01-19 23:38 UTC, Dansata commented
Profe, ya ajuste en el archivo la posiciòn del tag script y agreguè el archivo .js

2021-01-19 23:38 UTC, merged